import{n as h}from"./assets/vendor-OxPLOBIU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const u="raw_form_data_object",c="tasks_list_arr",d="current_theme";function a(e){const t=localStorage.getItem(e);if(!t)return null;try{return JSON.parse(t)}catch{return t}}function m(e,t){typeof t=="string"?localStorage.setItem(e,t):localStorage.setItem(e,JSON.stringify(t))}function g(e){localStorage.removeItem(e)}function f({id:e,title:t,description:i}){return`
        <li class="task-list-item" data-item-id="${e}"> 
            <button class="task-list-item-btn">Delete</button>
            <h3>${t}</h3>
            <p>${i}</p>
        </li>
        `}function L(e){return e.map(f).join(`
`)}const n={addItemForm:document.querySelector(".header-form"),itemList:document.querySelector(".tasks-list"),body:document.querySelector("body"),themeChangeBtn:document.getElementById("themeToggle")};n.addItemForm.addEventListener("input",function(e){const t=p(e);m(u,t)});n.addItemForm.addEventListener("submit",function(e){const t=p(e);if(t.title===""||t.description===""){alert("please complete form");return}const i={id:h().trim(),title:t.title.trim(),description:t.description.trim()},s=f(i),r=a(c)??[];m(c,[...r,i]),n.itemList.insertAdjacentHTML("beforeend",s),g(u),n.addItemForm.reset()});function p(e){e.preventDefault();const t=new FormData(e.currentTarget);return{title:t.get("taskName").trim(),description:t.get("taskDescription").trim()}}n.itemList.addEventListener("click",function(e){if(!e.target.classList.contains("task-list-item-btn"))return;const t=e.target.closest(".task-list-item"),i=t.dataset.itemId,r=(a(c)??[]).filter(o=>o.id!==i);m(c,[...r]),t.remove()});n.themeChangeBtn.addEventListener("click",function(){const e=n.body.classList;e.contains("theme-dark")?(e.replace("theme-dark","theme-light"),m(d,"theme-light")):(e.replace("theme-light","theme-dark"),m(d,"theme-dark"))});document.addEventListener("DOMContentLoaded",function(e){const t=a(u);n.addItemForm.elements.taskName.value=t!=null&&t.title?t.title.trim():"",n.addItemForm.elements.taskDescription.value=t!=null&&t.description?t.description.trim():"";const i=a(c)??[],s=L(i);n.itemList.innerHTML=s;const r=n.body.classList,o=a(d)??"theme-dark";r.contains("theme-dark")?r.replace("theme-dark",o):r.replace("theme-light",o)});
//# sourceMappingURL=index.js.map
