import{n as p}from"./assets/vendor-OxPLOBIU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const i={addItemForm:document.querySelector(".header-form"),itemList:document.querySelector(".tasks-list")},l="raw_form_data_object",c="tasks_list_arr";function m(e){const t=localStorage.getItem(e);if(!t)return null;try{return JSON.parse(t)}catch{return}}function u(e,t){typeof t=="string"?localStorage.setItem(e,t):localStorage.setItem(e,JSON.stringify(t))}function g(e){localStorage.removeItem(e)}function d({id:e,title:t,description:n}){return`
        <li class="task-list-item" data-item-id="${e}"> 
            <button class="task-list-item-btn">Delete</button>
            <h3>${t}</h3>
            <p>${n}</p>
        </li>
        `}function I(e){return e.map(d).join(`
`)}document.addEventListener("DOMContentLoaded",function(e){const t=m(l);i.addItemForm.elements.taskName.value=t!=null&&t.title?t.title:"",i.addItemForm.elements.taskDescription.value=t!=null&&t.description?t.description:"";const n=m(c)??[],s=I(n);i.itemList.innerHTML=s});i.addItemForm.addEventListener("input",function(e){const t=f(e);u(l,t)});i.addItemForm.addEventListener("submit",function(e){const t=f(e);if(t.title===""||t.description===""){alert("please complete form");return}const n={id:p(),title:t.title,description:t.description},s=d(n),r=m(c)??[];u(c,[...r,n]),i.itemList.insertAdjacentHTML("beforeend",s),g(l),i.addItemForm.reset()});function f(e){e.preventDefault();const t=new FormData(e.currentTarget);return{title:t.get("taskName"),description:t.get("taskDescription")}}
//# sourceMappingURL=index.js.map
